version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - heiglandreas
  ignore:
  - dependency-name: symfony/console
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.14
  - dependency-name: squizlabs/php_codesniffer
    versions:
    - 3.5.8
  - dependency-name: mockery/mockery
    versions:
    - 1.3.3
  - dependency-name: guzzlehttp/oauth-subscriber
    versions:
    - 0.4.0
